appName: secure-java21-gsm-api
svcName: secure-java21-gsm-api
nameSpace: apps
imageRepository: asadullahkhan/java-21-gsm-app
imageTag: "0.9.0"
replicaCount: 1
cpuRequests: 1
cpuLimits: 1
memoryRequests: 1G
memoryLimits: 1G
cluster: prod
executionID: "dgdfgdrg4356456"

LinitialDelay: 20
LprobePeriod: 10
RprobeUrl: hello
RprobePeriod: 10
RinitialDelay: 20

consul:
  enabled: false
  profiles: mcom,prod,ks

configmapEnabled: false

mapMount: /opt/application.properties
mapKey: application.properties
mapData:


serviceAccount:
  enabled: false
  name: secure-java21-gsm-api
  gcp_email: training-devops@gcp-hackathon-macys.iam.gserviceaccount.com

k8s_service_account:
  enabled: false

jksSecrets:
  enabled: false
  secretName: db-jks-prod
  jksPath: /jks

nodeselector:
  enabled: false
  value: standard

java:
  javaOpts: "-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -XX:MetaspaceSize=256m -XX:MaxRAMFraction=2 -XX:+UnlockExperimentalVMOptions  -Dclient.encoding.override=ISO-8859-1 -Dfile.encoding=ISO-8859-1"

ingress:
  enabled: true
  class: nginx
  domain: asadali.ie
  ilb: false

jmxExporter:
  enabled: false

jmxConsole:
  enabled: false

micrometer:
  enabled: false
  endpoint: /actuator/metrics/prometheus

serviceMonitor: false

cert:
  enabled: false

jksSecrets:
  enabled: false
  secretName: db-jks-int
  jksPath: /jks

keystoreSecrets:
  enabled: false

dtReleaseVersion:
  enabled: false

secret:
  enabled: true
  name: sa-secret
  mountPath: /secrets
  location: /secrets/service_account.json