appName: secure-java21-gsm-api
svcName: secure-java21-gsm-api
nameSpace: apps
imageRepository: asadullahkhan/java-21-gsm-app
imageTag: "1"
replicaCount: 1
cpuRequests: 1
cpuLimits: 1
memoryRequests: 1G
memoryLimits: 1G
cluster: prod
executionID: "dgdfgdrg4356456"

LinitialDelay: 45
LprobePeriod: 10
RprobeUrl: hello/
RprobePeriod: hello/
RinitialDelay: 45
RprobePeriod: 5

consul:
  enabled: false
  profiles: mcom,prod,ks

configmapEnabled: false

mapMount: /opt/application.properties
mapKey: application.properties
mapData:


serviceAccount:
  enabled: true
  name: msp-secure-java21-gsm-api-prod
  gcp_email: msp-secure-java21-gsm-api-prod@mtech-hs1-ecom-prod.iam.gserviceaccount.com

k8s_service_account:
  enabled: true

jksSecrets:
  enabled: false
  secretName: db-jks-prod
  jksPath: /jks

nodeselector:
  enabled: false
  value: standard

java:
  javaOpts: "-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -XX:MetaspaceSize=256m -XX:MaxRAMFraction=2 -XX:+UnlockExperimentalVMOptions  -Dclient.encoding.override=ISO-8859-1 -Dfile.encoding=ISO-8859-1"

ingress:
  enable: false
  ilb: false

jmxExporter:
  enabled: false

jmxConsole:
  enabled: false

micrometer:
  enabled: false
  endpoint: /actuator/metrics/prometheus

serviceMonitor: false

cert:
  enabled: false

jksSecrets:
  enabled: true
  secretName: db-jks-int
  jksPath: /jks

keystoreSecrets:
  enabled: false

dtReleaseVersion:
  enabled: true

secret:
  enabled: false
  name: sa-secret
  mountPath: /secrets
  location: /secrets/service_account.json