{{- if .Values.k8s_service_account.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcp_email }}
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.nameSpace }}
{{ end }}
