apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.appName }}
    layer: web
    release: {{ .Release.Name }}
    cluster: {{ .Values.cluster }}
    {{- if .Values.jmxExporter.enabled }}
    jmxExporter: enabled
    {{- end }}
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: {{ .Values.appName }}
    layer: web
    release: {{ .Release.Name }}
    cluster: {{ .Values.cluster }}
